version: "3"

services:
  eval:
    container_name: eval
    image: eval
    build:
      dockerfile: Dockerfile
      context: .
    volumes: # if you want to decrease your model download time, use this.
      - ../.cache/huggingface/:/root/.cache/huggingface/
      - ./static/:/app/static/
    ports:
      - "8000:8000"
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["3"] # You can choose which GPU to use
              capabilities: [gpu]
